### ISSUE TITLE
Converting @jonas txref to txid results in "computing…"

### ISSUE THREAD

**Issue by ChristopherA** [WebOfTrustInfo/txref-conversion-js#5]
@jonasschnelli publishes his TX1 enrollment in his twitter at: https://twitter.com/_jonasschnelli_ which is tx1-rk63-uvxf-9pqc-sy

If you put this into the playground's txref field, and click on convert, the txid field says "computing…".

Two bugs: it didn't reverse this function, and it stopped rather than reporting an error.

**Comment by ChristopherA** [comment]
I thought maybe my error was that I had not clicked on "mainnet" checkbox when I tried to reverse jonas' tx1. However, this didn't work.

**Comment by kimdhamilton** [comment]
This issue was moved to WebOfTrustInfo/btcr-tx-playground.github.io#5
